basic-app-web/models/Participant.php
<?php

namespace app\models;

use Yii;
use PDO;

class Participant extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'participant';
    }
}

?>

basic-app-web/models/ParticipantForm.php
<?php

namespace app\models;
use yii\base\Model;

class ParticipantForm extends Model
{
	public $name;
	public $email;
	public $valueX;
	public $valueY;
	public $valueZ;
	public $valueW;

	public function rules()
	{
		return [
			[['name', 'email', 'valueX', 'valueY', 'valueZ', 'valueW'], 'required', 'on' => ['insert', 'update']],
			['name', 'string', 'max' => 64, 'on' => ['insert', 'update']],
			['email', 'string', 'max' => 256, 'on' => ['insert', 'update']],
			['email', 'email', 'on' => ['insert', 'update']],
			['valueX', 'integer', 'min' => 1, 'max' => 33, 'on' => ['insert', 'update']],
			['valueY', 'integer', 'min' => 1, 'max' => 23, 'on' => ['insert', 'update']],
			['valueZ', 'integer', 'min' => 1, 'max' => 18, 'on' => ['insert', 'update']],
			['valueW', 'integer', 'min' => 1, 'max' => 13, 'on' => ['insert', 'update']],
		];
	}
}

?>

basic-app-web/controllers/ParticipantController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Participant;
use app\models\ParticipantForm;
use yii\helpers\ArrayHelper;

use Box\Spout\Common\Type;
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Writer\Style\StyleBuilder;
use Box\Spout\Writer\Style\Color;

class ParticipantController extends Controller
{
    public function actionIndex()
    {
        return $this->render('participant');
    }

    public function actionSearchParticipantList()
    {
        $rows = Participant::find()->orderBy($this->getParam('sort'))->offset($this->getParam('offset'))->limit($this->getParam('limit'))->all();
        $count = Participant::find()->count();

        $data = ArrayHelper::toArray($rows, [
            'app\models\Participant' => [
                'id',
                'name',
                'email',
                'x',
                'y',
                'z',
                'w'
            ],
        ]);

        $result = [
            'rows' => $data,
            'total' => $count
        ];

        return json_encode($result);
    }

    public function actionGetParticipantDetail()
    {
        $rows = Participant::findOne($this->getParam('id'));

        $data = ArrayHelper::toArray($rows, [
            'app\models\Participant' => [
                'id',
                'name',
                'email',
                'x',
                'y',
                'z',
                'w'
            ],
        ]);

        return json_encode($data);
    }

    public function actionInsertParticipant()
    {
        $participantForm = new ParticipantForm();

        $participantForm->name = $this->getParam('name');
        $participantForm->email = $this->getParam('email');
        $participantForm->valueX = $this->getParam('valueX');
        $participantForm->valueY = $this->getParam('valueY');
        $participantForm->valueZ = $this->getParam('valueZ');
        $participantForm->valueW = $this->getParam('valueW');
        $participantForm->scenario = 'insert';

        if ($participantForm->validate())
        {
            $participant = new Participant();

            $participant->name = $this->getParam('name');
            $participant->email = $this->getParam('email');
            $participant->x = $this->getParam('valueX');
            $participant->y = $this->getParam('valueY');
            $participant->z = $this->getParam('valueZ');
            $participant->w = $this->getParam('valueW');

            $participant->save();

            $result = [
                'errNum' => 0,
                'errStr' => 'Participant inserted successfully'
            ];

            return json_encode($result);
        }
        else
        {
            $result = [
                'errNum' => 1,
                'errStr' => $participantForm->errors
            ];

            return json_encode($result);
        }
    }

    public function actionUpdateParticipant()
    {
        $participantForm = new ParticipantForm();

        $participantForm->name = $this->getParam('name');
        $participantForm->email = $this->getParam('email');
        $participantForm->valueX = $this->getParam('valueX');
        $participantForm->valueY = $this->getParam('valueY');
        $participantForm->valueZ = $this->getParam('valueZ');
        $participantForm->valueW = $this->getParam('valueW');
        $participantForm->scenario = 'update';

        if ($participantForm->validate())
        {
            $participant = Participant::findOne($this->getParam('id'));

            $participant->name = $this->getParam('name');
            $participant->email = $this->getParam('email');
            $participant->x = $this->getParam('valueX');
            $participant->y = $this->getParam('valueY');
            $participant->z = $this->getParam('valueZ');
            $participant->w = $this->getParam('valueW');

            $participant->save();

            $result = [
                'errNum' => 0,
                'errStr' => 'Participant updated successfully'
            ];

            return json_encode($result);
        }
        else
        {
            $result = [
                'errNum' => 1,
                'errStr' => $participantForm->errors
            ];

            return json_encode($result);
        }
    }

    public function actionDeleteParticipant()
    {
        $participant = Participant::findOne($this->getParam('id'));
        $participant->delete();

        $result = [
            'errNum' => 0,
            'errStr' => 'Participant deleted successfully'
        ];

        return json_encode($result);
    }

    public function actionGenerateReport()
    {
        $participant = Participant::findOne($this->getParam('id'));
        $valInt = (int) (0.4 * $participant->x) + (0.6 * $participant->y / 2);
        $valNum = (int) (0.3 * $participant->z) + (0.7 * $participant->w / 2);

        if ($valInt > 5)
        {
            $valInt = 5;
        }
        else if ($valInt < 1)
        {
            $valInt = 1;
        }

        if ($valNum > 5)
        {
            $valNum = 5;
        }
        else if ($valNum < 1)
        {
            $valNum = 1;
        }

        $data = [];
        $dataInt = ['Aspek Intelegensi'];
        $dataNum = ['Aspek Numerical Ability'];

        for ($i = 0; $i < 5; $i++)
        {
            if ($valInt == $i + 1)
            {
                array_push($dataInt, 'v');
            }
            else
            {
                array_push($dataInt, '');
            }
        }

        for ($i = 0; $i < 5; $i++)
        {
            if ($valNum == $i + 1)
            {
                array_push($dataNum, 'v');
            }
            else
            {
                array_push($dataNum, '');
            }
        }

        array_push($data, $dataInt);
        array_push($data, $dataNum);

        $fileName = 'Report_' . $participant->name . '.xlsx';
        $dir = \Yii::getAlias('@app') . '/web/tmp/';

        if (!is_dir($dir))
        {
            mkdir($dir, 0775, true);
        }

        $dataTitle = [
            ['Nama', $participant->name],
            ['Email', $participant->email]
        ];
        
        $dataHeader = ['Aspek', '1', '2', '3', '4', '5'];

        $writer = WriterFactory::create(Type::XLSX);
        $writer->openToFile($dir . '/' . $fileName);
        
        $titleStyle = (new StyleBuilder())
            ->setFontBold()
            ->setFontSize(15)
            ->build();
            
        $paramStyle = (new StyleBuilder())
            ->setFontSize(11)
            ->setFontColor(Color::BLUE)
            ->build();
            
        $headerStyle = (new StyleBuilder())
            ->setFontBold()
            ->setFontSize(11)
            ->build();

        $sheet = $writer->getCurrentSheet();
        $writer->addRowsWithStyle($dataTitle, $titleStyle);
        $writer->addRow(['']);
        $writer->addRowWithStyle($dataHeader, $headerStyle);
        $writer->addRows($data);

        $writer->close();

        return Yii::$app->response->sendFile(Yii::getAlias('@app') . '/web/tmp/' . $fileName);
    }

    public function checkTags($val)
    {
        $val = strtolower($val);

        if (
            strpos($val, '<script') !== false ||
            strpos($val, '<!--') !== false ||
            strpos($val, '<html') !== false ||
            strpos($val, '<head') !== false ||
            strpos($val, '<body') !== false ||
            strpos($val, '<div') !== false)
        {
            return 1;
        }
    }

    public function checkArrayRecursive($paramValue, $flag)
    {
        if (!is_array($paramValue) && $this->checkTags($paramValue) && $flag == 1)
        {
            die(print('No HTML/Script injection allowed!'));
        }
        else if (is_array($paramValue))
        {
            foreach ($paramValue as $data)
            {
                $this->checkArrayRecursive($data, $flag);
            }
        }

        return;
    }


    public function getParam($paramKey, $flag = 1)
    {
        $paramValue = '';

        if (Yii::$app->request->isGet)
        {
            $paramValue = Yii::$app->request->getQueryParam($paramKey);
        }
        else if (Yii::$app->request->isPost)
        {
            $paramValue = Yii::$app->request->getBodyParam($paramKey);
        }

        $this->checkArrayRecursive($paramValue, $flag);

        return $paramValue;
    }
}

basic-app-web/views/participant/participant.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;

$this->title = 'Participant';
$this->params['breadcrumbs'][] = $this->title;
AppAsset::register($this);
?>



<div class="row">
	<div class="col-sm-3">
		<div class="float-left">
			<h1><?= Html::encode($this->title) ?></h1>
		</div>
	</div>
	<div class="col-sm-6"></div>
	<div class="col-sm-3" style="justify-content: right; align-items: center; display: flex">
		<div class="float-right">
			<button id="btnAdd" class="btn btn-sm btn-primary">Add Participant</button>
			<button id="btnFileManager" class="btn btn-sm btn-secondary">File Manager</button>
		</div>
	</div>
</div>
<br>
<div class="table-responsive">
	<table class="table" id="tblParticipantList" width="100%">
		<thead>
			<th data-field="name" data-sortable="false" data-align="center"><?= Yii::t('app', 'Name') ?></th>
			<th data-field="email" data-sortable="false" data-align="center"><?= Yii::t('app', 'Email') ?></th>
			<th data-field="x" data-sortable="false" data-align="center"><?= Yii::t('app', 'Value X') ?></th>
			<th data-field="y" data-sortable="false" data-align="center"><?= Yii::t('app', 'Value Y') ?></th>
			<th data-field="z" data-sortable="false" data-align="center"><?= Yii::t('app', 'Value Z') ?></th>
			<th data-field="w" data-sortable="false" data-align="center"><?= Yii::t('app', 'Value W') ?></th>
			<th data-formatter="actionFormatter"><?= Yii::t('app', 'Action') ?></th>
		</thead>
	</table>
</div>
<div class="modal fade" id="modalForm" aria-hidden="true" aria-labelledby="formLabel">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="formLabel"></h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form id="formData" class="form" autocomplete="off">
					<div class="form-group row required">
						<label class="col-sm-4 col-form-label"><?= Yii::t('app', 'Name') ?></label>
						<div class="col-sm-8">
							<input id="inputName" name="name" type="text" class="form-control form-control-sm" placeholder="<?= Yii::t('app', 'Name') ?>">
						</div>
					</div>

					<div class="form-group row required">
						<label class="col-sm-4 col-form-label"><?= Yii::t('app', 'Email') ?></label>
						<div class="col-sm-8">
							<input id="inputEmail" name="email" type="text" class="form-control form-control-sm" placeholder="<?= Yii::t('app', 'Email') ?>">
						</div>
					</div>

					<div class="form-group row required">
						<label class="col-sm-4 col-form-label"><?= Yii::t('app', 'Value X') ?></label>
						<div class="col-sm-8">
							<input id="inputX" name="x" type="text" class="form-control form-control-sm" placeholder="<?= Yii::t('app', 'Value X') ?>">
						</div>
					</div>

					<div class="form-group row required">
						<label class="col-sm-4 col-form-label"><?= Yii::t('app', 'Value Y') ?></label>
						<div class="col-sm-8">
							<input id="inputY" name="y" type="text" class="form-control form-control-sm" placeholder="<?= Yii::t('app', 'Value Y') ?>">
						</div>
					</div>

					<div class="form-group row required">
						<label class="col-sm-4 col-form-label"><?= Yii::t('app', 'Value Z') ?></label>
						<div class="col-sm-8">
							<input id="inputZ" name="z" type="text" class="form-control form-control-sm" placeholder="<?= Yii::t('app', 'Value Z') ?>">
						</div>
					</div>

					<div class="form-group row required">
						<label class="col-sm-4 col-form-label"><?= Yii::t('app', 'Value W') ?></label>
						<div class="col-sm-8">
							<input id="inputW" name="w" type="text" class="form-control form-control-sm" placeholder="<?= Yii::t('app', 'Value W') ?>">
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-sm btn-secondary" onclick="resetForm();"><?= Yii::t('app', 'Reset') ?></button>
				<button class="btn btn-sm btn-primary" onclick="submitForm()" type="submit"><?= Yii::t('app', 'Submit') ?></button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	self._oldData;
	self._action;

	$(document).ready(function()
	{
		searchParticipant();

		$('#btnAdd').on('click', function()
		{
			$('#formLabel').html('<?= Yii::t('app', 'Add Participant') ?>');
			self._action = 'add';
			resetForm();
			$('#modalForm').modal('show');
		});

		$('#btnFileManager').on('click', function()
		{
			window.location.href = '<?= Yii::$app->getUrlManager()->createUrl('file-manager') ?>';
		})
	});

	function submitForm()
	{
		if (self._action == 'add')
		{
			insertParticipant();
		}
		else if (self._action == 'edit')
		{
			updateParticipant();
		}
	}

	function resetForm()
	{
		$('#formData').trigger('reset');

		if (self._action == 'edit')
		{
			$('#inputName').val(self._oldData.name);
			$('#inputEmail').val(self._oldData.email);
			$('#inputX').val(self._oldData.x);
			$('#inputY').val(self._oldData.y);
			$('#inputZ').val(self._oldData.z);
			$('#inputW').val(self._oldData.w);
		}
	}

	function insertParticipant()
	{
		BootstrapModalWrapperFactory.confirm
		({
			title          : '<?= Yii::t('app', 'Confirm') ?>',
			message        : '<?= Yii::t('app', 'Are you sure you want to add this participant?') ?>' ,
			onConfirmAccept: function()
			{
				data = {
					name : $('#inputName').val(),
					email : $('#inputEmail').val(),
					valueX : $('#inputX').val(),
					valueY : $('#inputY').val(),
					valueZ : $('#inputZ').val(),
					valueW : $('#inputW').val()
				};

				$.ajax({
					type 		: 'POST',
					url			: '<?= Url::to(['participant/insert-participant']) ?>',
					data		: data,
					dataType	: 'JSON',
					success		: function (response)
					{
						BootstrapModalWrapperFactory.alert({
							title: '<?= Yii::t('app', 'Message') ?>',
							message: nl2br(msgConverter(response)),
							buttons: [
								{
									label: 'OK',
									cssClass: 'btn btn-primary',
									action: function (modalWrapper, button, buttonData, originalEvent)
									{
										modalWrapper.hide();
										if (response.errNum == 0)
										{
											resetForm();
											$('#modalForm').modal('hide');
											searchParticipant();
										}
									}
								},
							]
						});
					}
				})
			}
		});
	}

	function updateParticipant()
	{
		BootstrapModalWrapperFactory.confirm
		({
			title          : '<?= Yii::t('app', 'Confirm') ?>',
			message        : '<?= Yii::t('app', 'Are you sure you want to update this participant?') ?>' ,
			onConfirmAccept: function()
			{
				data = {
					id : self._oldData.id,
					name : $('#inputName').val(),
					email : $('#inputEmail').val(),
					valueX : $('#inputX').val(),
					valueY : $('#inputY').val(),
					valueZ : $('#inputZ').val(),
					valueW : $('#inputW').val()
				};

				$.ajax({
					type 		: 'POST',
					url			: '<?= Url::to(['participant/update-participant']) ?>',
					data		: data,
					dataType	: 'JSON',
					success		: function (response)
					{
						BootstrapModalWrapperFactory.alert({
							title: '<?= Yii::t('app', 'Message') ?>',
							message: nl2br(msgConverter(response)),
							buttons: [
								{
									label: 'OK',
									cssClass: 'btn btn-primary',
									action: function (modalWrapper, button, buttonData, originalEvent)
									{
										modalWrapper.hide();
										if (response.errNum == 0)
										{
											resetForm();
											$('#modalForm').modal('hide');
											searchParticipant();
										}
									}
								},
							]
						});
					}
				})
			}
		});
	}

	function deleteParticipant(id)
	{
		BootstrapModalWrapperFactory.confirm
		({
			title          : '<?= Yii::t('app', 'Confirm') ?>',
			message        : '<?= Yii::t('app', 'Are you sure you want to delete this participant?') ?>' ,
			onConfirmAccept: function()
			{
				data = {
					id : id
				};

				$.ajax({
					type 		: 'POST',
					url			: '<?= Url::to(['participant/delete-participant']) ?>',
					data		: data,
					dataType	: 'JSON',
					success		: function (response)
					{
						BootstrapModalWrapperFactory.alert({
							title: '<?= Yii::t('app', 'Message') ?>',
							message: nl2br(msgConverter(response)),
							buttons: [
								{
									label: 'OK',
									cssClass: 'btn btn-primary',
									action: function (modalWrapper, button, buttonData, originalEvent)
									{
										modalWrapper.hide();
										if (response.errNum == 0)
										{
											searchParticipant();
										}
									}
								},
							]
						});
					}
				})
			}
		});
	}

	function searchParticipant()
	{
		$('#tblParticipantList').bootstrapTable('destroy');
		$('#tblParticipantList').bootstrapTable
		({
			method          : 'POST',
			contentType     : 'application/x-www-form-urlencoded',
			sortName        : 'name',
			sortOrder       : 'asc',
			pagination      : true,
			sidePagination  : 'server',
			showRefresh     : false,
			singleSelect    : true,
			clickToSelect   : true,
			url             : '<?= Yii::$app->getUrlManager()->createUrl('participant/search-participant-list') ?>',
			responseHandler : function(res)
			{
				return res;
			},
			onLoadSuccess   		: function()
			{
				
			},
			onCheck         		: function()
			{
				
			},
			onUncheck       		: function()
			{
				
			},
			queryParams     		: function(p)
			{
				return p;
			},
			formatNoMatches : function()
			{
				return '<?= Yii::t('app', 'Data Not Found') ?>';
			}
		});
	}

	function getParticipantDetail(id)
	{
		data = {
			id : id
		}

		$.ajax({
			type 		: 'POST',
			url			: '<?= Url::to(['participant/get-participant-detail']) ?>',
			data		: data,
			dataType	: 'JSON',
			success		: function (response)
			{
				self._oldData = response;
				self._action = 'edit';
				resetForm();
				$('#formLabel').html('<?= Yii::t('app', 'Update Participant') ?>');
				$('#modalForm').modal('show');
			}
		})
	}

	function generateReport(id)
	{
		window.open('<?= Url::to(['participant/generate-report']) ?>' + '?id=' + id);

		// data = {
		// 	id : id
		// }

		// $.ajax({
		// 	type 		: 'POST',
		// 	url			: '<?= Url::to(['participant/generate-report']) ?>',
		// 	data		: data,
		// 	dataType	: 'JSON',
		// 	success		: function (response)
		// 	{
		// 		console.log(response);

		// 		element = '<a href="' + response.filePath + '">link</a>';
		// 		$('#generateLink').html(element);
		// 	}
		// })
	}

	function msgConverter(response)
	{
	    var output = '';

	    if (typeof(response.errStr) == 'object')
	    {
	        var property;

	        for (property in response.errStr)
	        {
	            output += response.errStr[property] + '<br>';
	        }
	    }
	    else
	    {
	        output += response.errStr;
	    }

	    if (response.errNum != 0)
	    {
	        output = '<p class="text-danger">' + output + '</p>';
	    }

	    return output;
	}

	function nl2br(str, is_xhtml) 
	{
	    var breakTag = (is_xhtml || typeof is_xhtml === 'undefined') ? '<br />' : '<br>';
	    return (str + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + breakTag + '$2');
	}

	function actionFormatter(value, row, index)
	{
		element = '\
			<button class="btn btn-sm btn-primary" onclick="generateReport(' + row.id + ')">Report</button>\
			<button class="btn btn-sm btn-secondary" onclick="getParticipantDetail(' + row.id + ')">Update</button>\
			<button class="btn btn-sm btn-danger" onclick="deleteParticipant(' + row.id + ')">Delete</button>\
		';

		return element;
	}
</script>